### ISSUE TITLE
[PE-D][Tester B] Invalid inputs for addtime and deletetime removes the text typed out

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-T10-3/tp#204]
When using invalid inputs for addtime and deletetime, the application clears the text typed out. This makes editing the text inconvenient as the user as to retype everything again.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Originalidk/ped#9

**Comment by Kailash201** [comment]
d
