### ISSUE TITLE
[PE-D][Tester B] addmeeting of different groups at clashing timings

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T10-3/tp#215]
When using addmeeting for different groups, applying the same timing for 2 separate groups will not result in a clash. This might result in conflicting schedules the user is unaware of.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Originalidk/ped#14

**Comment by Kailash201** [comment]
add in ug and dg as planned enhancement

**Comment by Kailash201** [comment]
d
